defaults: &defaults
  tld_length: 1
  available_languages: {en: 'English', pl: 'Polski'}

development:
  <<: *defaults
  domain: planer.dev

test:
  <<: *defaults
  domain: planer.test

production:
  <<: *defaults
  tld_length: 2
  domain: planer.rajewska.asia
