development:
  sessions:
    default:
      database: planer_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: planer_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: planer_production

